Repository astrochun/Evolution-of-Galaxies, pull requests merged in 2020-02, with the labels that each got.

#7 feature/commons_binning -> develop
  library.py
Labels: refactor

#12 feature/commons_R_temp_calc -> develop
  R_temp_calcul.py
Labels: bug, refactor

#16 feature/archives -> develop
  Archives/Composite Spectra Grid.ipynb
  Archives/binning_mag_mass.py
  Archives/composite_spectra.pdf
  Archives/galaxy_distribution.pdf
  Archives/hgamma_to_hbeta.py
  Archives/mass_distribution.PNG
  Archives/stack_check.py
Labels: organization

#18 release/v0.3.0
  Archives/Composite Spectra Grid.ipynb
  Archives/binning_mag_mass.py
  Archives/composite_spectra.pdf
  Archives/galaxy_distribution.pdf
  Archives/hgamma_to_hbeta.py
  Archives/mass_distribution.PNG
  Archives/stack_check.py
Labels: organization
